//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassXYZ.Vault.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassXYZ.Vault.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acknowledgement.
        /// </summary>
        internal static string about_acknowledgement {
            get {
                return ResourceManager.GetString("about_acknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PassXYZ.Vault is built on top of KPCLib which is a library changed based on KeePassLib. KPCLib enhanced KeePassLib so that it can be built as a PCL or .netstandard Library to run on .NET MAUI or Xamarin. KeePassLib is part of KeePass project developed by Dominik Reichl. The official website of KeePass is:.
        /// </summary>
        internal static string about_keepass {
            get {
                return ResourceManager.GetString("about_keepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information and source code of KPCLib can be found at:.
        /// </summary>
        internal static string about_kpclib {
            get {
                return ResourceManager.GetString("about_kpclib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Learn more.
        /// </summary>
        internal static string about_learn_more {
            get {
                return ResourceManager.GetString("about_learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright 2022, Roger Ye. All rights reserved..
        /// </summary>
        internal static string about_passxyz_copyright {
            get {
                return ResourceManager.GetString("about_passxyz_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PassXYZ.Vault is licensed under the GNU General Public License v3.0 . You may not use this file except in compliance with the License. You may obtain a copy of the License at.
        /// </summary>
        internal static string about_passxyz_license {
            get {
                return ResourceManager.GetString("about_passxyz_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This brief introduction is meant for those who are the new users of [PassXYZ](https://passxyz.github.io/). If you are a [KeePass](https://keepass.info/) veteran, you may skip this article and read another one called _In-depth understanding of PassXYZ_ on the [PassXYZ](https://passxyz.github.io/) website which can be found by clicking **Learn More** in menu item **Help**. 
        ///
        ///[PassXYZ](https://passxyz.github.io/) is similar to other password management software. It is quite easy to use. After the installatio [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string about_passxyz_usage {
            get {
                return ResourceManager.GetString("about_passxyz_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can submit problem report and get more information on how to use PassXYZ from the website below..
        /// </summary>
        internal static string about_passxyz_web {
            get {
                return ResourceManager.GetString("about_passxyz_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you encounter any problems when using PassXYZ, please send the problem report to PassXYZ Wechat public account or the email address passxyz@foxmail.com..
        /// </summary>
        internal static string about_problem_report {
            get {
                return ResourceManager.GetString("about_problem_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no problem report found..
        /// </summary>
        internal static string about_problem_report_not_found {
            get {
                return ResourceManager.GetString("about_problem_report_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send problem report.
        /// </summary>
        internal static string about_problem_report_send {
            get {
                return ResourceManager.GetString("about_problem_report_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your personal information management system.
        /// </summary>
        internal static string about_slogan {
            get {
                return ResourceManager.GetString("about_slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://passxyz.github.io/categories/Help/.
        /// </summary>
        internal static string about_url {
            get {
                return ResourceManager.GetString("about_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can also provide feedback through PassXYZ Wechat public account. PassXYZ Wechat public account is passxyz_kpclib. Or, you may wish to scan the QRcode below..
        /// </summary>
        internal static string about_wechat_info {
            get {
                return ResourceManager.GetString("about_wechat_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string action_id_add {
            get {
                return ResourceManager.GetString("action_id_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add icon.
        /// </summary>
        internal static string action_id_add_icon {
            get {
                return ResourceManager.GetString("action_id_add_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attach.
        /// </summary>
        internal static string action_id_attach {
            get {
                return ResourceManager.GetString("action_id_attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse.
        /// </summary>
        internal static string action_id_browse {
            get {
                return ResourceManager.GetString("action_id_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string action_id_cancel {
            get {
                return ResourceManager.GetString("action_id_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change icon.
        /// </summary>
        internal static string action_id_change_icon {
            get {
                return ResourceManager.GetString("action_id_change_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string action_id_close {
            get {
                return ResourceManager.GetString("action_id_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cloud Config.
        /// </summary>
        internal static string action_id_cloud_config {
            get {
                return ResourceManager.GetString("action_id_cloud_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy.
        /// </summary>
        internal static string action_id_copy {
            get {
                return ResourceManager.GetString("action_id_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cut.
        /// </summary>
        internal static string action_id_cut {
            get {
                return ResourceManager.GetString("action_id_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string action_id_delete {
            get {
                return ResourceManager.GetString("action_id_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable Sync.
        /// </summary>
        internal static string action_id_disable_sync {
            get {
                return ResourceManager.GetString("action_id_disable_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string action_id_edit {
            get {
                return ResourceManager.GetString("action_id_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable Sync.
        /// </summary>
        internal static string action_id_enable_sync {
            get {
                return ResourceManager.GetString("action_id_enable_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        internal static string action_id_export {
            get {
                return ResourceManager.GetString("action_id_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Barcode.
        /// </summary>
        internal static string action_id_generatebarcode {
            get {
                return ResourceManager.GetString("action_id_generatebarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QR code.
        /// </summary>
        internal static string action_id_generateqrcode {
            get {
                return ResourceManager.GetString("action_id_generateqrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide.
        /// </summary>
        internal static string action_id_hide {
            get {
                return ResourceManager.GetString("action_id_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import.
        /// </summary>
        internal static string action_id_import {
            get {
                return ResourceManager.GetString("action_id_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string action_id_login {
            get {
                return ResourceManager.GetString("action_id_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        internal static string action_id_logout {
            get {
                return ResourceManager.GetString("action_id_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move.
        /// </summary>
        internal static string action_id_move {
            get {
                return ResourceManager.GetString("action_id_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste.
        /// </summary>
        internal static string action_id_paste {
            get {
                return ResourceManager.GetString("action_id_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Properties.
        /// </summary>
        internal static string action_id_properties {
            get {
                return ResourceManager.GetString("action_id_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover.
        /// </summary>
        internal static string action_id_recover {
            get {
                return ResourceManager.GetString("action_id_recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string action_id_save {
            get {
                return ResourceManager.GetString("action_id_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan.
        /// </summary>
        internal static string action_id_scan {
            get {
                return ResourceManager.GetString("action_id_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string action_id_search {
            get {
                return ResourceManager.GetString("action_id_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Email.
        /// </summary>
        internal static string action_id_sendemail {
            get {
                return ResourceManager.GetString("action_id_sendemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share.
        /// </summary>
        internal static string action_id_share {
            get {
                return ResourceManager.GetString("action_id_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show.
        /// </summary>
        internal static string action_id_show {
            get {
                return ResourceManager.GetString("action_id_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string action_id_switchusers {
            get {
                return ResourceManager.GetString("action_id_switchusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string action_id_update {
            get {
                return ResourceManager.GetString("action_id_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset template.
        /// </summary>
        internal static string action_id_update_template {
            get {
                return ResourceManager.GetString("action_id_update_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string alert_id_no {
            get {
                return ResourceManager.GetString("alert_id_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string alert_id_ok {
            get {
                return ResourceManager.GetString("alert_id_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please confirm to delete.
        /// </summary>
        internal static string alert_id_remove {
            get {
                return ResourceManager.GetString("alert_id_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string alert_id_yes {
            get {
                return ResourceManager.GetString("alert_id_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PassXYZ.Vault.
        /// </summary>
        internal static string Appname {
            get {
                return ResourceManager.GetString("Appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Modified Date.
        /// </summary>
        internal static string database_modified_date {
            get {
                return ResourceManager.GetString("database_modified_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Modified Time.
        /// </summary>
        internal static string database_modified_time {
            get {
                return ResourceManager.GetString("database_modified_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database Name.
        /// </summary>
        internal static string database_name {
            get {
                return ResourceManager.GetString("database_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Railway Ticket 12306.
        /// </summary>
        internal static string entry_id_12306 {
            get {
                return ResourceManager.GetString("entry_id_12306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Agricultural Bank of China.
        /// </summary>
        internal static string entry_id_abc {
            get {
                return ResourceManager.GetString("entry_id_abc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Agricultural Bank of China - Credit Card.
        /// </summary>
        internal static string entry_id_abc_cc {
            get {
                return ResourceManager.GetString("entry_id_abc_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alipay.
        /// </summary>
        internal static string entry_id_alipay {
            get {
                return ResourceManager.GetString("entry_id_alipay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amazon.
        /// </summary>
        internal static string entry_id_amazon {
            get {
                return ResourceManager.GetString("entry_id_amazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apple ID.
        /// </summary>
        internal static string entry_id_apple {
            get {
                return ResourceManager.GetString("entry_id_apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baidu.
        /// </summary>
        internal static string entry_id_baidu {
            get {
                return ResourceManager.GetString("entry_id_baidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank Account.
        /// </summary>
        internal static string entry_id_bank_account {
            get {
                return ResourceManager.GetString("entry_id_bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank of China.
        /// </summary>
        internal static string entry_id_boc {
            get {
                return ResourceManager.GetString("entry_id_boc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank of China - Credit Card.
        /// </summary>
        internal static string entry_id_boc_cc {
            get {
                return ResourceManager.GetString("entry_id_boc_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Box.
        /// </summary>
        internal static string entry_id_box {
            get {
                return ResourceManager.GetString("entry_id_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a China Mobile.
        /// </summary>
        internal static string entry_id_c_mobile {
            get {
                return ResourceManager.GetString("entry_id_c_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a China Telecom.
        /// </summary>
        internal static string entry_id_c_telecom {
            get {
                return ResourceManager.GetString("entry_id_c_telecom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a China Unicom.
        /// </summary>
        internal static string entry_id_c_unicom {
            get {
                return ResourceManager.GetString("entry_id_c_unicom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a China Construction Bank.
        /// </summary>
        internal static string entry_id_ccb {
            get {
                return ResourceManager.GetString("entry_id_ccb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a China Construction Bank - Credit Card.
        /// </summary>
        internal static string entry_id_ccb_cc {
            get {
                return ResourceManager.GetString("entry_id_ccb_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificate of Marriage.
        /// </summary>
        internal static string entry_id_cert_of_marriage {
            get {
                return ResourceManager.GetString("entry_id_cert_of_marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 学信网.
        /// </summary>
        internal static string entry_id_chsi {
            get {
                return ResourceManager.GetString("entry_id_chsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a China Merchants Bank.
        /// </summary>
        internal static string entry_id_cmb {
            get {
                return ResourceManager.GetString("entry_id_cmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a China Merchants Bank - Credit Card.
        /// </summary>
        internal static string entry_id_cmb_cc {
            get {
                return ResourceManager.GetString("entry_id_cmb_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Merchants Securities.
        /// </summary>
        internal static string entry_id_cms {
            get {
                return ResourceManager.GetString("entry_id_cms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit Card.
        /// </summary>
        internal static string entry_id_credit_card {
            get {
                return ResourceManager.GetString("entry_id_credit_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Securities registration and Clearing.
        /// </summary>
        internal static string entry_id_csdc {
            get {
                return ResourceManager.GetString("entry_id_csdc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social Security.
        /// </summary>
        internal static string entry_id_csi {
            get {
                return ResourceManager.GetString("entry_id_csi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 社会统一用户基础平台.
        /// </summary>
        internal static string entry_id_csi_sz {
            get {
                return ResourceManager.GetString("entry_id_csi_sz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DBS.
        /// </summary>
        internal static string entry_id_dbs {
            get {
                return ResourceManager.GetString("entry_id_dbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DBS Credit Card.
        /// </summary>
        internal static string entry_id_dbs_cc {
            get {
                return ResourceManager.GetString("entry_id_dbs_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DBS Vickers.
        /// </summary>
        internal static string entry_id_dbs_vickers {
            get {
                return ResourceManager.GetString("entry_id_dbs_vickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DockerHub.
        /// </summary>
        internal static string entry_id_docker {
            get {
                return ResourceManager.GetString("entry_id_docker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driving license.
        /// </summary>
        internal static string entry_id_driving_license {
            get {
                return ResourceManager.GetString("entry_id_driving_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dropbox.
        /// </summary>
        internal static string entry_id_dropbox {
            get {
                return ResourceManager.GetString("entry_id_dropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evernote.
        /// </summary>
        internal static string entry_id_evernote {
            get {
                return ResourceManager.GetString("entry_id_evernote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facebook.
        /// </summary>
        internal static string entry_id_facebook {
            get {
                return ResourceManager.GetString("entry_id_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GitHub.
        /// </summary>
        internal static string entry_id_github {
            get {
                return ResourceManager.GetString("entry_id_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Google.
        /// </summary>
        internal static string entry_id_google {
            get {
                return ResourceManager.GetString("entry_id_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 港澳通行证.
        /// </summary>
        internal static string entry_id_hk_txz {
            get {
                return ResourceManager.GetString("entry_id_hk_txz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Huawei.
        /// </summary>
        internal static string entry_id_huawei {
            get {
                return ResourceManager.GetString("entry_id_huawei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Industrial and Commercial Bank of China.
        /// </summary>
        internal static string entry_id_icbc {
            get {
                return ResourceManager.GetString("entry_id_icbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Industrial and Commercial Bank of China - Credit Card.
        /// </summary>
        internal static string entry_id_icbc_cc {
            get {
                return ResourceManager.GetString("entry_id_icbc_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Card.
        /// </summary>
        internal static string entry_id_idcard {
            get {
                return ResourceManager.GetString("entry_id_idcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JD.com.
        /// </summary>
        internal static string entry_id_jingdong {
            get {
                return ResourceManager.GetString("entry_id_jingdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lim &amp; Tan.
        /// </summary>
        internal static string entry_id_limtan {
            get {
                return ResourceManager.GetString("entry_id_limtan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LinkedIn.
        /// </summary>
        internal static string entry_id_linkedin {
            get {
                return ResourceManager.GetString("entry_id_linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microsoft.
        /// </summary>
        internal static string entry_id_microsoft {
            get {
                return ResourceManager.GetString("entry_id_microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Netease.
        /// </summary>
        internal static string entry_id_netease {
            get {
                return ResourceManager.GetString("entry_id_netease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NuGet.
        /// </summary>
        internal static string entry_id_nuget {
            get {
                return ResourceManager.GetString("entry_id_nuget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 坚果云.
        /// </summary>
        internal static string entry_id_nutstore {
            get {
                return ResourceManager.GetString("entry_id_nutstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OCBC.
        /// </summary>
        internal static string entry_id_ocbc {
            get {
                return ResourceManager.GetString("entry_id_ocbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OCBC Credit Card.
        /// </summary>
        internal static string entry_id_ocbc_cc {
            get {
                return ResourceManager.GetString("entry_id_ocbc_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OneKey.
        /// </summary>
        internal static string entry_id_onekey {
            get {
                return ResourceManager.GetString("entry_id_onekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passport.
        /// </summary>
        internal static string entry_id_passport {
            get {
                return ResourceManager.GetString("entry_id_passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How to use PassXYZ ?.
        /// </summary>
        internal static string entry_id_passxyz_usage {
            get {
                return ResourceManager.GetString("entry_id_passxyz_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PayPal.
        /// </summary>
        internal static string entry_id_paypal {
            get {
                return ResourceManager.GetString("entry_id_paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PICC人保.
        /// </summary>
        internal static string entry_id_picc {
            get {
                return ResourceManager.GetString("entry_id_picc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ping An Bank.
        /// </summary>
        internal static string entry_id_pingan {
            get {
                return ResourceManager.GetString("entry_id_pingan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ping An Bank - Credit Card.
        /// </summary>
        internal static string entry_id_pingan_cc {
            get {
                return ResourceManager.GetString("entry_id_pingan_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QQ.
        /// </summary>
        internal static string entry_id_qq {
            get {
                return ResourceManager.GetString("entry_id_qq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CDP.
        /// </summary>
        internal static string entry_id_sgx {
            get {
                return ResourceManager.GetString("entry_id_sgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SingPass.
        /// </summary>
        internal static string entry_id_singpass {
            get {
                return ResourceManager.GetString("entry_id_singpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skype.
        /// </summary>
        internal static string entry_id_skype {
            get {
                return ResourceManager.GetString("entry_id_skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP Services.
        /// </summary>
        internal static string entry_id_spgroup {
            get {
                return ResourceManager.GetString("entry_id_spgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 申万宏源.
        /// </summary>
        internal static string entry_id_sywg {
            get {
                return ResourceManager.GetString("entry_id_sywg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 深圳住房公积金.
        /// </summary>
        internal static string entry_id_sz_hpf {
            get {
                return ResourceManager.GetString("entry_id_sz_hpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 深圳市地方税务局.
        /// </summary>
        internal static string entry_id_szlt {
            get {
                return ResourceManager.GetString("entry_id_szlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 深圳燃气.
        /// </summary>
        internal static string entry_id_szrq {
            get {
                return ResourceManager.GetString("entry_id_szrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taobao.
        /// </summary>
        internal static string entry_id_taobao {
            get {
                return ResourceManager.GetString("entry_id_taobao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter.
        /// </summary>
        internal static string entry_id_twitter {
            get {
                return ResourceManager.GetString("entry_id_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UOB.
        /// </summary>
        internal static string entry_id_uob {
            get {
                return ResourceManager.GetString("entry_id_uob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UOB Credit Card.
        /// </summary>
        internal static string entry_id_uob_cc {
            get {
                return ResourceManager.GetString("entry_id_uob_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle license.
        /// </summary>
        internal static string entry_id_vehicle_license {
            get {
                return ResourceManager.GetString("entry_id_vehicle_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WeChat.
        /// </summary>
        internal static string entry_id_wechat {
            get {
                return ResourceManager.GetString("entry_id_wechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 微博.
        /// </summary>
        internal static string entry_id_weibo {
            get {
                return ResourceManager.GetString("entry_id_weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xiaomi.
        /// </summary>
        internal static string entry_id_xiaomi {
            get {
                return ResourceManager.GetString("entry_id_xiaomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yahoo.
        /// </summary>
        internal static string entry_id_yahoo {
            get {
                return ResourceManager.GetString("entry_id_yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 宜停车.
        /// </summary>
        internal static string entry_id_ytc {
            get {
                return ResourceManager.GetString("entry_id_ytc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration is not correct..
        /// </summary>
        internal static string error_message_config1 {
            get {
                return ResourceManager.GetString("error_message_config1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill in the correct configuration..
        /// </summary>
        internal static string error_message_config2 {
            get {
                return ResourceManager.GetString("error_message_config2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid URL format..
        /// </summary>
        internal static string error_message_invalid_url {
            get {
                return ResourceManager.GetString("error_message_invalid_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please accept privacy notice to use this app..
        /// </summary>
        internal static string error_message_privacy_notice {
            get {
                return ResourceManager.GetString("error_message_privacy_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a user first..
        /// </summary>
        internal static string export_error1 {
            get {
                return ResourceManager.GetString("export_error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 支付宝生活号.
        /// </summary>
        internal static string field_id_alipay {
            get {
                return ResourceManager.GetString("field_id_alipay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All In One Net Password.
        /// </summary>
        internal static string field_id_all_in_one_net_p {
            get {
                return ResourceManager.GetString("field_id_all_in_one_net_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ATM PIN.
        /// </summary>
        internal static string field_id_atm_pin {
            get {
                return ResourceManager.GetString("field_id_atm_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup Data.
        /// </summary>
        internal static string field_id_backup_data {
            get {
                return ResourceManager.GetString("field_id_backup_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera.
        /// </summary>
        internal static string field_id_camera {
            get {
                return ResourceManager.GetString("field_id_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CVV.
        /// </summary>
        internal static string field_id_cvv {
            get {
                return ResourceManager.GetString("field_id_cvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string field_id_email {
            get {
                return ResourceManager.GetString("field_id_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        internal static string field_id_file {
            get {
                return ResourceManager.GetString("field_id_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gallery.
        /// </summary>
        internal static string field_id_gallery {
            get {
                return ResourceManager.GetString("field_id_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hostname, such as sftp.passxyz.com.
        /// </summary>
        internal static string field_id_hostname {
            get {
                return ResourceManager.GetString("field_id_hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotline.
        /// </summary>
        internal static string field_id_hotline {
            get {
                return ResourceManager.GetString("field_id_hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internet Banking Password.
        /// </summary>
        internal static string field_id_internet_banking_p {
            get {
                return ResourceManager.GetString("field_id_internet_banking_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internet Banking Username.
        /// </summary>
        internal static string field_id_internet_banking_u {
            get {
                return ResourceManager.GetString("field_id_internet_banking_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local Data.
        /// </summary>
        internal static string field_id_local_data {
            get {
                return ResourceManager.GetString("field_id_local_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mobile.
        /// </summary>
        internal static string field_id_mobile {
            get {
                return ResourceManager.GetString("field_id_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string field_id_name {
            get {
                return ResourceManager.GetString("field_id_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notes.
        /// </summary>
        internal static string field_id_notes {
            get {
                return ResourceManager.GetString("field_id_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string field_id_password {
            get {
                return ResourceManager.GetString("field_id_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Password.
        /// </summary>
        internal static string field_id_payment_password {
            get {
                return ResourceManager.GetString("field_id_payment_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Banking PIN.
        /// </summary>
        internal static string field_id_phone_banking_pin {
            get {
                return ResourceManager.GetString("field_id_phone_banking_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PIN.
        /// </summary>
        internal static string field_id_pin {
            get {
                return ResourceManager.GetString("field_id_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Port.
        /// </summary>
        internal static string field_id_port {
            get {
                return ResourceManager.GetString("field_id_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query PIN.
        /// </summary>
        internal static string field_id_query_pin {
            get {
                return ResourceManager.GetString("field_id_query_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remote Data.
        /// </summary>
        internal static string field_id_remote_data {
            get {
                return ResourceManager.GetString("field_id_remote_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remote folder, such as /home/tester/pxvault/.
        /// </summary>
        internal static string field_id_remote_folder {
            get {
                return ResourceManager.GetString("field_id_remote_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service Password.
        /// </summary>
        internal static string field_id_service_password {
            get {
                return ResourceManager.GetString("field_id_service_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template.
        /// </summary>
        internal static string field_id_template {
            get {
                return ResourceManager.GetString("field_id_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string field_id_title {
            get {
                return ResourceManager.GetString("field_id_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trading Password.
        /// </summary>
        internal static string field_id_trading_pin {
            get {
                return ResourceManager.GetString("field_id_trading_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a U Key PIN.
        /// </summary>
        internal static string field_id_u_key_pin {
            get {
                return ResourceManager.GetString("field_id_u_key_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL.
        /// </summary>
        internal static string field_id_url {
            get {
                return ResourceManager.GetString("field_id_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string field_id_username {
            get {
                return ResourceManager.GetString("field_id_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WeChat Official Account.
        /// </summary>
        internal static string field_id_wechat {
            get {
                return ResourceManager.GetString("field_id_wechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protected field.
        /// </summary>
        internal static string field_name_switch_label_isProtected {
            get {
                return ResourceManager.GetString("field_name_switch_label_isProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PassXYZ.Resx.passxyz_en-us.t4xyz.
        /// </summary>
        internal static string file_name_template {
            get {
                return ResourceManager.GetString("file_name_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please use fingerprint to login.
        /// </summary>
        internal static string fingerprint_login_message {
            get {
                return ResourceManager.GetString("fingerprint_login_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank.
        /// </summary>
        internal static string group_id_bank {
            get {
                return ResourceManager.GetString("group_id_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document.
        /// </summary>
        internal static string group_id_document {
            get {
                return ResourceManager.GetString("group_id_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primary Services.
        /// </summary>
        internal static string group_id_primary_services {
            get {
                return ResourceManager.GetString("group_id_primary_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recycle Bin.
        /// </summary>
        internal static string group_id_recyclebin {
            get {
                return ResourceManager.GetString("group_id_recyclebin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Results.
        /// </summary>
        internal static string group_id_search {
            get {
                return ResourceManager.GetString("group_id_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data file.
        /// </summary>
        internal static string import_data_file {
            get {
                return ResourceManager.GetString("import_data_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data file (with key file).
        /// </summary>
        internal static string import_data_file_ex {
            get {
                return ResourceManager.GetString("import_data_file_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot import this file!.
        /// </summary>
        internal static string import_error_msg {
            get {
                return ResourceManager.GetString("import_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot import this file! This user alreay exists..
        /// </summary>
        internal static string import_error_user_exits {
            get {
                return ResourceManager.GetString("import_error_user_exits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import key file.
        /// </summary>
        internal static string import_keyfile {
            get {
                return ResourceManager.GetString("import_keyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan key file QR code.
        /// </summary>
        internal static string import_keyfile_scan {
            get {
                return ResourceManager.GetString("import_keyfile_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a KeePass or PassXYZ data file.
        /// </summary>
        internal static string import_message1 {
            get {
                return ResourceManager.GetString("import_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cloud Storage Type.
        /// </summary>
        internal static string item_prop_cloud_type {
            get {
                return ResourceManager.GetString("item_prop_cloud_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icon Name.
        /// </summary>
        internal static string item_prop_icon_name {
            get {
                return ResourceManager.GetString("item_prop_icon_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry.
        /// </summary>
        internal static string item_subtype_entry {
            get {
                return ResourceManager.GetString("item_subtype_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group.
        /// </summary>
        internal static string item_subtype_group {
            get {
                return ResourceManager.GetString("item_subtype_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notes.
        /// </summary>
        internal static string item_subtype_notes {
            get {
                return ResourceManager.GetString("item_subtype_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PxEntry.
        /// </summary>
        internal static string item_subtype_pxentry {
            get {
                return ResourceManager.GetString("item_subtype_pxentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template.
        /// </summary>
        internal static string item_subtype_template {
            get {
                return ResourceManager.GetString("item_subtype_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Using templates.
        /// </summary>
        internal static string item_subtype_using_template {
            get {
                return ResourceManager.GetString("item_subtype_using_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attachment.
        /// </summary>
        internal static string label_id_attachment {
            get {
                return ResourceManager.GetString("label_id_attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom icon.
        /// </summary>
        internal static string label_id_custom_icon {
            get {
                return ResourceManager.GetString("label_id_custom_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login failed.
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesar.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tu Usuario y Password para acceder a PassXYZ..
        /// </summary>
        internal static string LoginPageWelcomeMessage {
            get {
                return ResourceManager.GetString("LoginPageWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Recovery.
        /// </summary>
        internal static string menu_id_data_recovery {
            get {
                return ResourceManager.GetString("menu_id_data_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string menu_id_help {
            get {
                return ResourceManager.GetString("menu_id_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string menu_id_settings {
            get {
                return ResourceManager.GetString("menu_id_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template.
        /// </summary>
        internal static string menu_id_template {
            get {
                return ResourceManager.GetString("menu_id_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string menu_id_user {
            get {
                return ResourceManager.GetString("menu_id_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string menu_id_users {
            get {
                return ResourceManager.GetString("menu_id_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot logout now, .
        /// </summary>
        internal static string message_id_alert_logout_disable {
            get {
                return ResourceManager.GetString("message_id_alert_logout_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot remove the current user.
        /// </summary>
        internal static string message_id_alert_removing_current_user {
            get {
                return ResourceManager.GetString("message_id_alert_removing_current_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  is a system group. System groups cannot be removed!.
        /// </summary>
        internal static string message_id_alert_removing_system_group {
            get {
                return ResourceManager.GetString("message_id_alert_removing_system_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to save the changes?.
        /// </summary>
        internal static string message_id_alert_saving {
            get {
                return ResourceManager.GetString("message_id_alert_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please add attachments from.
        /// </summary>
        internal static string message_id_attachment_options {
            get {
                return ResourceManager.GetString("message_id_attachment_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill in cloud storage configuration..
        /// </summary>
        internal static string message_id_cloud_config {
            get {
                return ResourceManager.GetString("message_id_cloud_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot edit binary.
        /// </summary>
        internal static string message_id_edit_binary {
            get {
                return ResourceManager.GetString("message_id_edit_binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot save this icon. Icon size should be larger than 96 pixels..
        /// </summary>
        internal static string message_id_icon_size {
            get {
                return ResourceManager.GetString("message_id_icon_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current user will be logout after the import. Please confirm to import.
        /// </summary>
        internal static string message_id_import_confirmation {
            get {
                return ResourceManager.GetString("message_id_import_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A new database with Device Lock enabled will be created. Please assign a username for the new database..
        /// </summary>
        internal static string message_id_import_device_lock_desc {
            get {
                return ResourceManager.GetString("message_id_import_device_lock_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to import .
        /// </summary>
        internal static string message_id_import_failure {
            get {
                return ResourceManager.GetString("message_id_import_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please login first before import a.
        /// </summary>
        internal static string message_id_import_login_request {
            get {
                return ResourceManager.GetString("message_id_import_login_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OTP secret cannot be imported..
        /// </summary>
        internal static string message_id_import_otp_failure {
            get {
                return ResourceManager.GetString("message_id_import_otp_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to overwrite the existing OTP secret?.
        /// </summary>
        internal static string message_id_import_otp_overwrite {
            get {
                return ResourceManager.GetString("message_id_import_otp_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OTP secret is saved.
        /// </summary>
        internal static string message_id_import_otp_saved {
            get {
                return ResourceManager.GetString("message_id_import_otp_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a After import, please login using the original master password. Please create a user name for the data file:.
        /// </summary>
        internal static string message_id_importData {
            get {
                return ResourceManager.GetString("message_id_importData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have successfully imported data file.
        /// </summary>
        internal static string message_id_importDataSuccess {
            get {
                return ResourceManager.GetString("message_id_importDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data file can be recovered from backup file. If cannot work, please try to recover from cloud file.
        ///
        ///- **Local Data** can be recovered from remote data or backup data
        ///- **Remote Data** can be recovered using local data.
        /// </summary>
        internal static string message_id_recover_datafile {
            get {
                return ResourceManager.GetString("message_id_recover_datafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot synchronize file.
        /// </summary>
        internal static string message_id_sync_failure {
            get {
                return ResourceManager.GetString("message_id_sync_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synchronization completed.
        /// </summary>
        internal static string message_id_sync_success {
            get {
                return ResourceManager.GetString("message_id_sync_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template has been updated..
        /// </summary>
        internal static string message_id_update_template {
            get {
                return ResourceManager.GetString("message_id_update_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter field name here.
        /// </summary>
        internal static string ph_id_key {
            get {
                return ResourceManager.GetString("ph_id_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your password.
        /// </summary>
        internal static string ph_id_password {
            get {
                return ResourceManager.GetString("ph_id_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your title.
        /// </summary>
        internal static string ph_id_title {
            get {
                return ResourceManager.GetString("ph_id_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter field value here.
        /// </summary>
        internal static string ph_id_value {
            get {
                return ResourceManager.GetString("ph_id_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # Privacy Notice
        ///
        ///
        ///This privacy notice discloses the privacy practices for PassXYZ application and our websites:
        ///- PassXYZ, PassXYZ Cloud and PassXYZ.Vault
        ///- https://passxyz.github.io
        ///- https://github.com/passxyz
        ///
        ///## Information Collection, Use, and Sharing 
        ///
        ///This website is built using the services provided by GitHub. It is a static website and does not collect any information. Please refer to the GitHub Privacy Statement about the agreement before you use GitHub services.
        ///
        ///PassXYZ application  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string privacy_notice {
            get {
                return ResourceManager.GetString("privacy_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please choose an item to be created: .
        /// </summary>
        internal static string pt_id_choosetemplate {
            get {
                return ResourceManager.GetString("pt_id_choosetemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a user to switch.
        /// </summary>
        internal static string pt_id_switchusers {
            get {
                return ResourceManager.GetString("pt_id_switchusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting users.
        /// </summary>
        internal static string settings_deleting_users {
            get {
                return ResourceManager.GetString("settings_deleting_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have selected to use an empty master password..
        /// </summary>
        internal static string settings_empty_password {
            get {
                return ResourceManager.GetString("settings_empty_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export database to other devices or cloud storage.
        /// </summary>
        internal static string settings_export_remark {
            get {
                return ResourceManager.GetString("settings_export_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export database.
        /// </summary>
        internal static string settings_export_title {
            get {
                return ResourceManager.GetString("settings_export_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fingerprint is not supported.
        /// </summary>
        internal static string settings_fingerprint_disabled {
            get {
                return ResourceManager.GetString("settings_fingerprint_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable fingerprint to unlock.
        /// </summary>
        internal static string settings_fingerprint_remark {
            get {
                return ResourceManager.GetString("settings_fingerprint_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fingerprint setup.
        /// </summary>
        internal static string settings_fingerprint_title {
            get {
                return ResourceManager.GetString("settings_fingerprint_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security Settings.
        /// </summary>
        internal static string settings_keyFileField_Key {
            get {
                return ResourceManager.GetString("settings_keyFileField_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device Lock enabled. Device Lock Key can be exported.
        /// </summary>
        internal static string settings_keyFileField_Value1 {
            get {
                return ResourceManager.GetString("settings_keyFileField_Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device Lock disabled.
        /// </summary>
        internal static string settings_keyFileField_Value2 {
            get {
                return ResourceManager.GetString("settings_keyFileField_Value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device Lock.
        /// </summary>
        internal static string settings_keyFileField_Value3 {
            get {
                return ResourceManager.GetString("settings_keyFileField_Value3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password, name etc..
        /// </summary>
        internal static string settings_manage_db_remark {
            get {
                return ResourceManager.GetString("settings_manage_db_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage database.
        /// </summary>
        internal static string settings_manage_db_title {
            get {
                return ResourceManager.GetString("settings_manage_db_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add or delete users.
        /// </summary>
        internal static string settings_manage_users_remark {
            get {
                return ResourceManager.GetString("settings_manage_users_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset your master password.
        /// </summary>
        internal static string settings_manage_users_reset_password {
            get {
                return ResourceManager.GetString("settings_manage_users_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage users.
        /// </summary>
        internal static string settings_manage_users_title {
            get {
                return ResourceManager.GetString("settings_manage_users_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a suitable merge method.
        /// </summary>
        internal static string settings_merge_method_remark {
            get {
                return ResourceManager.GetString("settings_merge_method_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Merge method: .
        /// </summary>
        internal static string settings_merge_method_title {
            get {
                return ResourceManager.GetString("settings_merge_method_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login to synchronize using OneDrive.
        /// </summary>
        internal static string settings_onedrive_remark {
            get {
                return ResourceManager.GetString("settings_onedrive_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OneDrive Username is.
        /// </summary>
        internal static string settings_onedrive_status {
            get {
                return ResourceManager.GetString("settings_onedrive_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Using OneDrive sync current database.
        /// </summary>
        internal static string settings_onedrive_title {
            get {
                return ResourceManager.GetString("settings_onedrive_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device Lock Key.
        /// </summary>
        internal static string settings_security_DeviceLockKey {
            get {
                return ResourceManager.GetString("settings_security_DeviceLockKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create Device Lock Key.
        /// </summary>
        internal static string settings_security_DLK_Created_failure {
            get {
                return ResourceManager.GetString("settings_security_DLK_Created_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device Lock Key is created successfully.
        /// </summary>
        internal static string settings_security_DLK_Created_success {
            get {
                return ResourceManager.GetString("settings_security_DLK_Created_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need a Device Lock Key to login as user .
        /// </summary>
        internal static string settings_security_DLK_message1 {
            get {
                return ResourceManager.GetString("settings_security_DLK_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This QR code is not a PassXYZ Device Lock Key.
        /// </summary>
        internal static string settings_security_DLK_Wrong_Format {
            get {
                return ResourceManager.GetString("settings_security_DLK_Wrong_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong Device Lock Key. It is for user.
        /// </summary>
        internal static string settings_security_DLK_Wrong_User {
            get {
                return ResourceManager.GetString("settings_security_DLK_Wrong_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device Lock Key QR code.
        /// </summary>
        internal static string settings_security_generate_QRCode {
            get {
                return ResourceManager.GetString("settings_security_generate_QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permission.
        /// </summary>
        internal static string settings_security_permission {
            get {
                return ResourceManager.GetString("settings_security_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a permission is required to use this app.
        /// </summary>
        internal static string settings_security_permission_desc {
            get {
                return ResourceManager.GetString("settings_security_permission_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maybe Later.
        /// </summary>
        internal static string settings_security_permission_negative {
            get {
                return ResourceManager.GetString("settings_security_permission_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanned QR code.
        /// </summary>
        internal static string settings_security_scan_result {
            get {
                return ResourceManager.GetString("settings_security_scan_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export Device Lock Key to a file.
        /// </summary>
        internal static string settings_security_share_keyfile {
            get {
                return ResourceManager.GetString("settings_security_share_keyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Using Device Lock.
        /// </summary>
        internal static string settings_security_UsingDeviceLock {
            get {
                return ResourceManager.GetString("settings_security_UsingDeviceLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sychornize with other devices through messaging app.
        /// </summary>
        internal static string settings_sync_remark {
            get {
                return ResourceManager.GetString("settings_sync_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sychronize database.
        /// </summary>
        internal static string settings_sync_title {
            get {
                return ResourceManager.GetString("settings_sync_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create, import or delete.
        /// </summary>
        internal static string settings_template_remark {
            get {
                return ResourceManager.GetString("settings_template_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage template.
        /// </summary>
        internal static string settings_template_title {
            get {
                return ResourceManager.GetString("settings_template_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time before locking database when the application is inactive.
        /// </summary>
        internal static string settings_timer_remark {
            get {
                return ResourceManager.GetString("settings_timer_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer setup.
        /// </summary>
        internal static string settings_timer_title {
            get {
                return ResourceManager.GetString("settings_timer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hour.
        /// </summary>
        internal static string settings_timer_unit_hour {
            get {
                return ResourceManager.GetString("settings_timer_unit_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minutes.
        /// </summary>
        internal static string settings_timer_unit_minutes {
            get {
                return ResourceManager.GetString("settings_timer_unit_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seconds.
        /// </summary>
        internal static string settings_timer_unit_seconds {
            get {
                return ResourceManager.GetString("settings_timer_unit_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated password successfully..
        /// </summary>
        internal static string settings_updated_password {
            get {
                return ResourceManager.GetString("settings_updated_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating password ....
        /// </summary>
        internal static string settings_updating_password {
            get {
                return ResourceManager.GetString("settings_updating_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up failed, please check the format of username and password.
        /// </summary>
        internal static string SignUpErrorMessage {
            get {
                return ResourceManager.GetString("SignUpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user already exists. You can try to login with this username..
        /// </summary>
        internal static string SignUpErrorMessage1 {
            get {
                return ResourceManager.GetString("SignUpErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Password and Password confirmation do not exactly match..
        /// </summary>
        internal static string SignUpErrorMessage2 {
            get {
                return ResourceManager.GetString("SignUpErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu puedes crear un nuevo usuario en la base de datos o importar uno de KeePass..
        /// </summary>
        internal static string SignUpPageMessage {
            get {
                return ResourceManager.GetString("SignUpPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string SignUpPageTitle {
            get {
                return ResourceManager.GetString("SignUpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully created a new user.
        /// </summary>
        internal static string SiguUpMessage {
            get {
                return ResourceManager.GetString("SiguUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cloud storage configuration.
        /// </summary>
        internal static string title_cloud_config {
            get {
                return ResourceManager.GetString("title_cloud_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File on cloud drive.
        /// </summary>
        internal static string user_id_cloud {
            get {
                return ResourceManager.GetString("user_id_cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synchronization is disabled.
        /// </summary>
        internal static string user_id_disabled {
            get {
                return ResourceManager.GetString("user_id_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local file.
        /// </summary>
        internal static string user_id_local {
            get {
                return ResourceManager.GetString("user_id_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synchronized with cloud.
        /// </summary>
        internal static string user_id_synced {
            get {
                return ResourceManager.GetString("user_id_synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synchronizing with cloud ....
        /// </summary>
        internal static string user_id_syncing {
            get {
                return ResourceManager.GetString("user_id_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
